apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  namespace: {{ template "helm-guestbook.name" . }}
  labels:
    app: {{ template "helm-guestbook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    my-lable: Edit-by-argo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: my-port
  selector:
    app: {{ template "helm-guestbook.name" . }}
    release: {{ .Release.Name }}
